### ISSUE TITLE
feat(spark): Nebula spark connector does not support spark 3.4+

### ISSUE THREAD

**Issue by SemyonSinchenko** [apache/incubator-graphar#583]
### Describe the enhancement requested

We should decide what to do with it. At the moment it is a part of Spark CI.

```
Exception in thread "main" java.lang.RuntimeException: Your current spark version 3.4.3 is not supported by the current NebulaGraph Spark Connector.
 please visit https://github.com/vesoft-inc/nebula-spark-connector#version-match to know which Connector you need.
 
	at com.vesoft.nebula.connector.utils.SparkValidate$.validate(SparkValidate.scala:15)
	at com.vesoft.nebula.connector.connector.package$NebulaDataFrameReader.nebula(package.scala:34)
	at org.apache.graphar.example.Nebula2GraphAr$.readVertexDF(Nebula2GraphAr.scala:135)
	at org.apache.graphar.example.Nebula2GraphAr$.readAndPutDataIntoWriter(Nebula2GraphAr.scala:83)
	at org.apache.graphar.example.Nebula2GraphAr$.main(Nebula2GraphAr.scala:53)
	at org.apache.graphar.example.Nebula2GraphAr.main(Nebula2GraphAr.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1020)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:192)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:215)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

### Component(s)

Spark

**Comment by SemyonSinchenko** [comment]
[Code](https://github.com/vesoft-inc/nebula-spark-connector/blob/master/nebula-spark-connector_3.0/src/main/scala/com/vesoft/nebula/connector/package.scala#L34):
```scala
SparkValidate.validate("3.0.*", "3.1.*", "3.2.*", "3.3.*")
```
